# Generated by Django 2.2.2 on 2020-03-10 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=5000)),
                ('name', models.CharField(max_length=90)),
                ('email', models.CharField(max_length=222)),
                ('address', models.CharField(max_length=222)),
                ('city', models.CharField(max_length=222)),
                ('state', models.CharField(max_length=222)),
                ('zip_code', models.CharField(max_length=222)),
            ],
        ),
    ]
